spring.application.name=pnrchecker
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

rapidapi.key=051b254f49msh889170dc5608d09p1dff22jsn0b660aa06c6b
rapidapi.host=irctc-indian-railway-pnr-status.p.rapidapi.com
server.port=${PORT:8080}